apiVersion: v2
name: onecx-data-orchestrator-bff
version: 0.0.0
appVersion: 0.0.0
description: OneCX Data Orchestrator BFF
keywords:
  - data-orchestrator
sources:
  - https://github.com/onecx/onecx-data-orchestrator-bff
maintainers:
  - name: Tkit Developer
    email: tkit_dev@1000kit.org
dependencies:
  - name: helm-quarkus-app
    alias: app
    version: ^0
    repository: oci://ghcr.io/onecx/charts